/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


export const styles:any[] = [''];
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvdmFncmFudC9sb2dveC9tdHgtcHJvamVjdC9zcmMvYXBwL21hbmFnZXRyYWRleC9jb21wb25lbnRzL3RyYW5zbGF0ZS90cmFuc2xhdGUuY29tcG9uZW50LmNzcy5zaGltLm5nc3R5bGUudHMiLCJ2ZXJzaW9uIjozLCJzb3VyY2VSb290IjoiIiwic291cmNlcyI6WyJuZzovLy9ob21lL3ZhZ3JhbnQvbG9nb3gvbXR4LXByb2plY3Qvc3JjL2FwcC9tYW5hZ2V0cmFkZXgvY29tcG9uZW50cy90cmFuc2xhdGUvdHJhbnNsYXRlLmNvbXBvbmVudC5jc3MiXSwic291cmNlc0NvbnRlbnQiOlsiICJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7OyJ9
