/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as i0 from './translate.component.css.shim.ngstyle';
import * as i1 from '@angular/core';
import * as i2 from './translate.component';
const styles_TranslateComponent:any[] = [i0.styles];
export const RenderType_TranslateComponent:i1.RendererType2 = i1.ɵcrt({encapsulation:0,
    styles:styles_TranslateComponent,data:{}});
export function View_TranslateComponent_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'p',([] as any[]),
      (null as any),(null as any),(null as any),(null as any),(null as any))),(_l()(),
      i1.ɵted((null as any),['\n  translate works!\n'])),(_l()(),i1.ɵted((null as any),
      ['\n']))],(null as any),(null as any));
}
export function View_TranslateComponent_Host_0(_l:any):i1.ɵViewDefinition {
  return i1.ɵvid(0,[(_l()(),i1.ɵeld(0,(null as any),(null as any),1,'managetradex-translate',
      ([] as any[]),(null as any),(null as any),(null as any),View_TranslateComponent_0,
      RenderType_TranslateComponent)),i1.ɵdid(114688,(null as any),0,i2.TranslateComponent,
      ([] as any[]),(null as any),(null as any))],(_ck,_v) => {
    _ck(_v,1,0);
  },(null as any));
}
export const TranslateComponentNgFactory:i1.ComponentFactory<i2.TranslateComponent> = i1.ɵccf('managetradex-translate',
    i2.TranslateComponent,View_TranslateComponent_Host_0,{},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL2hvbWUvdmFncmFudC9sb2dveC9tdHgtcHJvamVjdC9zcmMvYXBwL21hbmFnZXRyYWRleC9jb21wb25lbnRzL3RyYW5zbGF0ZS90cmFuc2xhdGUuY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL2hvbWUvdmFncmFudC9sb2dveC9tdHgtcHJvamVjdC9zcmMvYXBwL21hbmFnZXRyYWRleC9jb21wb25lbnRzL3RyYW5zbGF0ZS90cmFuc2xhdGUuY29tcG9uZW50LnRzIiwibmc6Ly8vaG9tZS92YWdyYW50L2xvZ294L210eC1wcm9qZWN0L3NyYy9hcHAvbWFuYWdldHJhZGV4L2NvbXBvbmVudHMvdHJhbnNsYXRlL3RyYW5zbGF0ZS5jb21wb25lbnQuaHRtbCIsIm5nOi8vL2hvbWUvdmFncmFudC9sb2dveC9tdHgtcHJvamVjdC9zcmMvYXBwL21hbmFnZXRyYWRleC9jb21wb25lbnRzL3RyYW5zbGF0ZS90cmFuc2xhdGUuY29tcG9uZW50LnRzLlRyYW5zbGF0ZUNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIjxwPlxuICB0cmFuc2xhdGUgd29ya3MhXG48L3A+XG4iLCI8bWFuYWdldHJhZGV4LXRyYW5zbGF0ZT48L21hbmFnZXRyYWRleC10cmFuc2xhdGU+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7O29CQ0FBO01BQUEsd0VBQUc7YUFBQSw0Q0FFQztNQUFBOzs7b0JDRko7TUFBQTttQ0FBQSxVQUFBO01BQUE7SUFBQTs7OzsifQ==
